## External Secret placeholder ##

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akv-external-secret-read-sp
  namespace: ekho-external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: akv-sp-secret-store
  target:
    name: external-secret-read-sp
  data:
  - secretKey: loginpw
    remoteRef:
      key: secret/loginPassword
  - secretKey: apiurl
    remoteRef:
      key: secret/apiUrl
  - secretKey: clientid
    remoteRef:
      key: secret/clientId
  - secretKey: clientsecret
    remoteRef:
      key: secret/clientSecret
  - secretKey: loginuname
    remoteRef:
      key: secret/loginUsername
  - secretKey: pullsecret
    remoteRef:
      key: secret/pullSecret