## ClusterSecretStore - For Read
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: akv-cluster-secret-read
  namespace: ekho-external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  provider:
    azurekv:
      tenantId: 64dc69e4-d083-49fc-9569-ebece1dd1408
      vaultUrl: "https://dd-aro-cluster-akv-demo.vault.azure.net/"
      authSecretRef:
        clientId:
          name: akv-sp-read
          key: ClientID
          namespace: ekho-external-secrets
        clientSecret:
          name: akv-sp-read
          key: ClientSecret
          namespace: ekho-external-secrets
---
## ClusterSecretStore - For Push
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: akv-cluster-secret-push
  namespace: ekho-external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  provider:
    azurekv:
      tenantId: 64dc69e4-d083-49fc-9569-ebece1dd1408
      vaultUrl: "https://dd-aro-cluster-akv-demo.vault.azure.net/"
      authSecretRef:
        clientId:
          name: akv-sp-push
          key: ClientID
          namespace: ekho-external-secrets
        clientSecret:
          name: akv-sp-push
          key: ClientSecret
          namespace: ekho-external-secrets